[package]
edition = "2024"
name = "build-scripts"
version = "0.1.0"

[dependencies]
clap = {version = "4.5.45", features = ["derive"]}
filesystem = {path = "../library/filesystem", features = ["dyn-io-error"]}
